export const Images = {
    backButton: require("../../../assets/backbutton.png"),
    demoProfile1: require("../../../assets/1.jpg"),
    demoProfile2: require("../../../assets/2.jpg"),
    demoProfile3: require("../../../assets/3.jpg"),
    demoProfile4: require("../../../assets/4.jpg"),
    demoProfile5: require("../../../assets/5.jpg"),
    demoProfile6: require("../../../assets/6.jpg"),
    onboard_vector: require("../../../assets/onboardVector.png"),
    goto_icon: require("../../../assets/gotobutton.png"),
    add: require("../../../assets/ekle.png"),
    homeBar: require("../../../assets/homeBar.png"),
    academyBar: require("../../../assets/academyBar.png"),
    peopleBar: require("../../../assets/peopleBar.png"),
    profileBar: require("../../../assets/profileBar.png"),
    youtube: require("../../../assets/youtube.png"),
    yargi: require("../../../assets/yargi.png"),
    ipekyol: require("../../../assets/ipekyol.png"),
    adidas: require("../../../assets/adidas.png"),
    kisafilm: require("../../../assets/kisafilm.png"),
    blackflag: require("../../../assets/blackflag.png"),
    whiteflag: require("../../../assets/whiteflag.png"),
    specialme: require("../../../assets/specialme.png"),
    mainsearch: require("../../../assets/mainsearch.png"),
    sorticon: require("../../../assets/sorticon.png"),
    adidasss : require("../../../assets/adidasss.jpg"),
    minus : require("../../../assets/minus.png"),


}